# especifica la version del lenguaje
version: '3.9'

# define los servicios
services:
  app:
    build:               
      context: .         #va a crear el archivo de docker en el directorio actual
    ports:
      - "8000:8000"       # coloca el puerto 8000 de la PC dentro del contenedor de Docker
    volumes:
      - ./app:/app      # define como se mapea el sistema de archivos dentro del contenedor
    environment:
      ENVIRONMENT: "development" 
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"