---
name: Checks
on: [push] # define el comando de Git que inicia la accion
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # define el sistema operativo que GitHub va a usar para los tests
    steps:
      - name: Login to Docker Hub # paso 1: nos logueamos
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Checkout # paso 2: le damos acceso al codigo a GitHub
        uses: actions/checkout@v4
      - name: Test # paso 3: corremos los unitest
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
